stages:
  - test
  - build


test:unit:
  stage: test
  tags:
    - local
  image: golang:1.25-alpine
  script:
    - for i in 1 2 3 4 5; do apk add --no-cache git gcc musl-dev && break || echo "Attempt $i failed, retrying in 5s..." && sleep 5; done
    - go mod download
    - go test -v -race -short -cover ./...
  coverage: '/coverage: \d+\.\d+% of statements/'

test:lint:
  stage: test
  tags:
    - local
  image: golangci/golangci-lint:latest
  script:
    - golangci-lint run ./...
  allow_failure: true

build:backend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"gitlab-ci-token\",\"password\":\"${CI_JOB_TOKEN}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile ${CI_PROJECT_DIR}/Dockerfile --destination ${CI_REGISTRY_IMAGE}-backend:${CI_COMMIT_SHORT_SHA} --destination ${CI_REGISTRY_IMAGE}-backend:latest

build:frontend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"gitlab-ci-token\",\"password\":\"${CI_JOB_TOKEN}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context ${CI_PROJECT_DIR}/ui --dockerfile ${CI_PROJECT_DIR}/ui/Dockerfile --destination ${CI_REGISTRY_IMAGE}-frontend:${CI_COMMIT_SHORT_SHA} --destination ${CI_REGISTRY_IMAGE}-frontend:latest
